server:
  port: 8080
  servlet:
    context-path: /test-app
  ssl:
    key-store: /etc/letsencrypt/live/vinuaws.ml/keystore.p12
    key-store-password:
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true
